<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_INSTANCE Refreshed On SEPT 2020_svg-outline</name>
   <tag></tag>
   <elementGuidId>d2b0cb02-ed54-43e0-88ee-43d2bb61f5e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>path.svg-outline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-outline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M11.656,16.938h24.75v1H11.656v-1ZM11.625,24.25h24.75v1H11.625v-1Zm0,7.25h24.75v1H11.625v-1Z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_UISmmLink::icon&quot;)/g[4]/path[@class=&quot;svg-outline&quot;]</value>
   </webElementProperties>
</WebElementEntity>
