<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>680e7ea0-a6b8-49b7-935a-63bcff97d4d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Paypal&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wt-account']/div/div[2]/div[2]/form/fieldset/div/span/label/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.wp.americansoftwarecontracts.com/wp-content/themes/workreap/workreap/images/payouts/paypal.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Paypal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt-account&quot;)/div[@class=&quot;wt-tabsinfo wt-email-settings&quot;]/div[@class=&quot;wt-settingscontent&quot;]/div[@class=&quot;wt-formtheme wt-userform payout-holder&quot;]/form[@class=&quot;wt-payout-settings&quot;]/fieldset[1]/div[@class=&quot;wt-checkboxholder&quot;]/span[@class=&quot;wt-radio&quot;]/label[1]/figure[@class=&quot;wt-userlistingimg&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt-account']/div/div[2]/div[2]/form/fieldset/div/span/label/figure/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Paypal']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/figure/img</value>
   </webElementXpaths>
</WebElementEntity>
